name: Generate Dashboard
on:
  workflow_run:
    workflows: ["Robot Framework Tests"]
    types:
      - completed

jobs:
  process-artifact:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        ref: "refs/heads/reporting"
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install  -r requirements.txt
    - name: Download artifact from triggering workflow
      uses: actions/download-artifact@v4
      with:
        name: rfoutput
        path: output/
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Process artifact with foo
      run: |
        find .
        robotdashboard -o output/output.xml -d ./db/robot_results.db -n index.html

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add db/robot_results.db
        git diff --cached --quiet || git commit -m "Processed artifact and updated files"
        git push origin HEAD:reporting

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: 'index.html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
